FROM archlinux:base-devel

# NAME = docker.io/evertheylen/arch-with-code-server

# Parts taken from https://github.com/containers/image_build/blob/main/podman/Containerfile

# Fresh build: podman build --no-cache -t docker.io/evertheylen/arch-with-code-server .
# Login to docker registry: podman login docker.io
# Deploy: podman push docker.io/evertheylen/arch-with-code-server

# ------------------------ Install stuff ------------------------

RUN pacman-key --init
RUN pacman -Sy --noconfirm archlinux-keyring
RUN pacman -Su --noconfirm

RUN useradd --create-home --system aurbuilder
RUN echo "aurbuilder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN systemd-machine-id-setup

# Install paru from AUR (takes a relatively long time to compile)
RUN pacman -S --noconfirm git
RUN sudo -u aurbuilder bash -c "git clone https://aur.archlinux.org/paru.git /tmp/paru && cd /tmp/paru && makepkg -si --noconfirm" \
    && rm -rf /tmp/paru

# Install code-server (takes a bit of time to compile)
RUN sudo -u aurbuilder bash -c "paru -S --noconfirm code-server"

# System mgmt
RUN pacman -S --noconfirm pkgfile
# Podman (in podman)
RUN pacman -S --noconfirm podman fuse-overlayfs
# Terminal stuff
RUN pacman -S --noconfirm less nano fish ripgrep tree htop bat fzf tmux tree jq
# Databases
RUN pacman -S --noconfirm postgresql postgis pgcli
# Programming
RUN pacman -S --noconfirm python uv python-pexpect python-pillow python-poetry python-distutils-extra jedi-language-server python-jedi nodejs npm go jupyterlab clang rust-analyzer gopls shellcheck julia
# Debugging
RUN pacman -S --noconfirm strace valgrind gdb
# Network
RUN pacman -S --noconfirm openssh openvpn traceroute nmap wget tcpdump socat net-tools rsync rclone bind
# Various
RUN pacman -S --noconfirm zip unzip ffmpeg imagemagick man-db doctl

# Clean up
RUN pacman -Sc --noconfirm

# Problem while starting various systemd services (e.g. postgres):
#   postgresql.service: Failed to keep CAP_SYS_ADMIN: Operation not permitted
#   postgresql.service: Failed at step USER spawning /usr/bin/postgresql-check-db-dir: Operation not permitted
#
# Solution: systemd is requesting CAP_SYS_ADMIN and fails.
#   ProtectKernelModules=true
#   ProtectKernelTunables=true
#   PrivateDevices=true
#   RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
#   RestrictNamespaces=true
#   RestrictRealtime=true
#   SystemCallArchitectures=native
# This issue goes into more detail: https://github.com/systemd/systemd/issues/34565
RUN sed -i -E 's/^(ProtectKernelModules|ProtectKernelTunables|PrivateDevices|RestrictAddressFamilies|RestrictNamespaces|RestrictRealtime|SystemCallArchitectures)/# \1/' /usr/lib/systemd/system/postgresql.service

RUN npm install --global pnpm

RUN mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers /var/lib/shared/vfs-images /var/lib/shared/vfs-layers && \
  touch /var/lib/shared/overlay-images/images.lock && \
  touch /var/lib/shared/overlay-layers/layers.lock && \
  touch /var/lib/shared/vfs-images/images.lock && \
  touch /var/lib/shared/vfs-layers/layers.lock


# ------------------------ Configs ------------------------

RUN pkgfile --update

RUN echo 'include /usr/share/nano/*.nanorc' >> /etc/nanorc

RUN mkdir -p /var/lib/systemd/linger

USER root
CMD [ "/sbin/init" ]

# Like quay.io/podman/stable (comments removed)
RUN cat <<EOF > /etc/containers/storage.conf
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"

[storage.options]
additionalimagestores = ["/var/lib/shared", "/usr/lib/containers/storage"]
pull_options = {enable_partial_images = "true", use_hard_links = "false", ostree_repos=""}

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev,fsync=0"

EOF


# Also like quay.io/podman/stable (comments removed)
RUN cat <<EOF >/etc/containers/containers.conf
[containers]
netns="host"
userns="host"
ipcns="host"
utsns="host"
cgroupns="host"
cgroups="disabled"
log_driver = "k8s-file"

[engine]
cgroup_manager = "cgroupfs"
events_logger="file"
runtime="crun"

EOF

# Also for rootless PINP, make pings work
RUN setcap cap_setuid,cap_setgid=eip /usr/sbin/newuidmap &&\
  setcap cap_setuid,cap_setgid=eip /usr/sbin/newgidmap &&\
  setcap cap_net_raw+p $(which ping)

COPY ./setup-user.sh /usr/bin/setup-user.sh
COPY ./start-shell.sh /usr/bin/start-shell.sh
RUN chmod +x /usr/bin/start-shell.sh /usr/bin/setup-user.sh

LABEL probox.setup_user="/usr/bin/setup-user.sh"
LABEL probox.start_shell="/usr/bin/start-shell.sh"
